version: '3.1'
services:
    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379

    mongo_db:
        image: mongo:latest
        restart: always
        ports:
            - 27018:27017
        # volumes:
        #     - ./mongodb-data/:/data/db
            
    backend:
        build:
            context: ../Server
            dockerfile: Dockerfile
        restart: always
        environment:
            REDIS_HOST: redis
            PORT: 4000
            JWT_ACCESS_KEY: ducanh123
            JWT_REFRESH_KEY: ducanh2211
            BASE_URL_CLIENT: http://18.217.246.135/
            # BASE_URL_SERVER: http://localhost:4000
            DB_URI: mongodb://mongo_db:27017/database_ecommerce
        depends_on:
            - mongo_db
            - redis
        ports:
            - 4000:4000
        expose:
            - 4000
        
    nginx:
        image: nginx:1.23.3
        ports:
          - 80:80
        volumes:
          - ../Client/build:/usr/share/nginx/html
          - ./default.conf:/etc/nginx/conf.d/default.conf
        

        # docker compose -p ecommerce-epressjs-mongodb up -d         


